// src/common/constants/error-codes.enum.ts
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_COIN_ID = 'INVALID_COIN_ID',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  PRICE_NOT_FOUND = 'PRICE_NOT_FOUND',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  BATCH_TIMEOUT = 'BATCH_TIMEOUT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
